/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lixinyuyin_monosyllabicdetect_view_GraphData */

#ifndef _Included_com_lixinyuyin_monosyllabicdetect_view_GraphData
#define _Included_com_lixinyuyin_monosyllabicdetect_view_GraphData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lixinyuyin_monosyllabicdetect_view_GraphData
 * Method:    readParam
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lixinyuyin_monosyllabicdetect_view_GraphData_readParam
  (JNIEnv *, jobject);

/*
 * Class:     com_lixinyuyin_monosyllabicdetect_view_GraphData
 * Method:    saveWdrcInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_lixinyuyin_monosyllabicdetect_view_GraphData_saveWdrcInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_lixinyuyin_monosyllabicdetect_view_GraphData
 * Method:    saveIntVal
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_lixinyuyin_monosyllabicdetect_view_GraphData_saveIntVal
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_lixinyuyin_monosyllabicdetect_view_GraphData
 * Method:    saveDoubleVal
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_lixinyuyin_monosyllabicdetect_view_GraphData_saveDoubleVal
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
